map.tileMap = {
  tileSets: {
    0: {
      img: "fences",
      name: "tileset 0",
      gridWidth: 4,
      gridHeight: 4,
      tileCount: 16,
      tileData: {
        "0-0": { x: 0, y: 0, tilesetIdx: "0", tileSymbol: "¥" },
        "1-0": { x: 1, y: 0, tilesetIdx: "0", tileSymbol: "¦" },
        "2-0": { x: 2, y: 0, tilesetIdx: "0", tileSymbol: "§" },
        "3-0": { x: 3, y: 0, tilesetIdx: "0", tileSymbol: "¨" },
        "0-1": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©" },
        "1-1": { x: 1, y: 1, tilesetIdx: "0", tileSymbol: "ª" },
        "2-1": { x: 2, y: 1, tilesetIdx: "0", tileSymbol: "«" },
        "3-1": { x: 3, y: 1, tilesetIdx: "0", tileSymbol: "¬" },
        "0-2": { x: 0, y: 2, tilesetIdx: "0", tileSymbol: "­" },
        "1-2": { x: 1, y: 2, tilesetIdx: "0", tileSymbol: "®" },
        "2-2": { x: 2, y: 2, tilesetIdx: "0", tileSymbol: "¯" },
        "3-2": { x: 3, y: 2, tilesetIdx: "0", tileSymbol: "°" },
        "0-3": { x: 0, y: 3, tilesetIdx: "0", tileSymbol: "±" },
        "1-3": { x: 1, y: 3, tilesetIdx: "0", tileSymbol: "²" },
        "2-3": { x: 2, y: 3, tilesetIdx: "0", tileSymbol: "³" },
        "3-3": { x: 3, y: 3, tilesetIdx: "0", tileSymbol: "´" },
      },
      symbolStartIdx: 0,
      tileSize: 64,
      tags: {},
      frames: {},
      description: "n/a",
      width: 256,
      height: 256,
    },
    1: {
      img: "hills",
      name: "tileset 1",
      gridWidth: 6,
      gridHeight: 6,
      tileCount: 36,
      tileData: {
        "0-0": { x: 0, y: 0, tilesetIdx: "1", tileSymbol: "µ" },
        "1-0": { x: 1, y: 0, tilesetIdx: "1", tileSymbol: "¶" },
        "2-0": { x: 2, y: 0, tilesetIdx: "1", tileSymbol: "·" },
        "3-0": { x: 3, y: 0, tilesetIdx: "1", tileSymbol: "¸" },
        "4-0": { x: 4, y: 0, tilesetIdx: "1", tileSymbol: "¹" },
        "5-0": { x: 5, y: 0, tilesetIdx: "1", tileSymbol: "º" },
        "0-1": { x: 0, y: 1, tilesetIdx: "1", tileSymbol: "»" },
        "1-1": { x: 1, y: 1, tilesetIdx: "1", tileSymbol: "¼" },
        "2-1": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½" },
        "3-1": { x: 3, y: 1, tilesetIdx: "1", tileSymbol: "¾" },
        "4-1": { x: 4, y: 1, tilesetIdx: "1", tileSymbol: "¿" },
        "5-1": { x: 5, y: 1, tilesetIdx: "1", tileSymbol: "À" },
        "0-2": { x: 0, y: 2, tilesetIdx: "1", tileSymbol: "Á" },
        "1-2": { x: 1, y: 2, tilesetIdx: "1", tileSymbol: "Â" },
        "2-2": { x: 2, y: 2, tilesetIdx: "1", tileSymbol: "Ã" },
        "3-2": { x: 3, y: 2, tilesetIdx: "1", tileSymbol: "Ä" },
        "4-2": { x: 4, y: 2, tilesetIdx: "1", tileSymbol: "Å" },
        "5-2": { x: 5, y: 2, tilesetIdx: "1", tileSymbol: "Æ" },
        "0-3": { x: 0, y: 3, tilesetIdx: "1", tileSymbol: "Ç" },
        "1-3": { x: 1, y: 3, tilesetIdx: "1", tileSymbol: "È" },
        "2-3": { x: 2, y: 3, tilesetIdx: "1", tileSymbol: "É" },
        "3-3": { x: 3, y: 3, tilesetIdx: "1", tileSymbol: "Ê" },
        "4-3": { x: 4, y: 3, tilesetIdx: "1", tileSymbol: "Ë" },
        "5-3": { x: 5, y: 3, tilesetIdx: "1", tileSymbol: "Ì" },
        "0-4": { x: 0, y: 4, tilesetIdx: "1", tileSymbol: "Í" },
        "1-4": { x: 1, y: 4, tilesetIdx: "1", tileSymbol: "Î" },
        "2-4": { x: 2, y: 4, tilesetIdx: "1", tileSymbol: "Ï" },
        "3-4": { x: 3, y: 4, tilesetIdx: "1", tileSymbol: "Ð" },
        "4-4": { x: 4, y: 4, tilesetIdx: "1", tileSymbol: "Ñ" },
        "5-4": { x: 5, y: 4, tilesetIdx: "1", tileSymbol: "Ò" },
        "0-5": { x: 0, y: 5, tilesetIdx: "1", tileSymbol: "Ó" },
        "1-5": { x: 1, y: 5, tilesetIdx: "1", tileSymbol: "Ô" },
        "2-5": { x: 2, y: 5, tilesetIdx: "1", tileSymbol: "Õ" },
        "3-5": { x: 3, y: 5, tilesetIdx: "1", tileSymbol: "Ö" },
        "4-5": { x: 4, y: 5, tilesetIdx: "1", tileSymbol: "×" },
        "5-5": { x: 5, y: 5, tilesetIdx: "1", tileSymbol: "Ø" },
      },
      symbolStartIdx: 16,
      tileSize: 64,
      tags: {},
      frames: {},
      description: "n/a",
      width: 383,
      height: 383,
    },
    2: {
      img: "water",
      name: "tileset 2",
      gridWidth: 4,
      gridHeight: 1,
      tileCount: 4,
      tileData: {
        "0-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù" },
        "1-0": { x: 1, y: 0, tilesetIdx: "2", tileSymbol: "Ú" },
        "2-0": { x: 2, y: 0, tilesetIdx: "2", tileSymbol: "Û" },
        "3-0": { x: 3, y: 0, tilesetIdx: "2", tileSymbol: "Ü" },
      },
      symbolStartIdx: 52,
      tileSize: 64,
      tags: {},
      frames: {},
      description: "n/a",
      width: 256,
      height: 64,
    },
  },
  maps: {
    Map_1: {
      layers: [
        {
          tiles: {
            "0-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-2": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-3": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-4": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-5": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-6": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-7": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-8": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-9": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "0-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "2-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "3-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "4-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "5-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "6-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "7-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "8-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "9-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-11": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-9": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-8": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-7": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "12-7": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "12-6": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "12-5": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-5": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-4": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-3": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-6": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-2": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "11-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "9-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "8-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "7-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "6-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "5-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "4-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "3-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "2-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-0": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-2": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-3": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-4": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-5": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-6": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-7": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-8": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-9": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "1-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "2-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "3-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "4-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "5-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "6-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "7-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "8-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "9-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-10": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-9": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-8": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-7": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-6": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-5": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-4": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-3": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-2": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "10-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "9-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "8-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "7-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "6-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "5-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "4-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "3-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
            "2-1": { x: 0, y: 0, tilesetIdx: "2", tileSymbol: "Ù", isFlippedX: false },
          },
          visible: true,
          name: "Layer1",
          animatedTiles: {},
          opacity: 1,
        },
        {
          tiles: {
            "2-9": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "1-10": { x: 1, y: 2, tilesetIdx: "1", tileSymbol: "Â", isFlippedX: false },
            "2-10": { x: 2, y: 2, tilesetIdx: "1", tileSymbol: "Ã", isFlippedX: false },
            "1-9": { x: 1, y: 1, tilesetIdx: "1", tileSymbol: "¼", isFlippedX: false },
            "3-10": { x: 3, y: 2, tilesetIdx: "1", tileSymbol: "Ä", isFlippedX: false },
            "3-9": { x: 2, y: 4, tilesetIdx: "1", tileSymbol: "Ï", isFlippedX: false },
            "4-9": { x: 2, y: 2, tilesetIdx: "1", tileSymbol: "Ã", isFlippedX: false },
            "3-8": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "1-8": { x: 1, y: 1, tilesetIdx: "1", tileSymbol: "¼", isFlippedX: false },
            "4-8": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "1-1": { x: 1, y: 0, tilesetIdx: "1", tileSymbol: "¶", isFlippedX: false },
            "2-1": { x: 2, y: 0, tilesetIdx: "1", tileSymbol: "·", isFlippedX: false },
            "3-1": { x: 2, y: 0, tilesetIdx: "1", tileSymbol: "·", isFlippedX: false },
            "4-1": { x: 2, y: 0, tilesetIdx: "1", tileSymbol: "·", isFlippedX: false },
            "5-1": { x: 2, y: 0, tilesetIdx: "1", tileSymbol: "·", isFlippedX: false },
            "6-1": { x: 2, y: 0, tilesetIdx: "1", tileSymbol: "·", isFlippedX: false },
            "7-1": { x: 2, y: 0, tilesetIdx: "1", tileSymbol: "·", isFlippedX: false },
            "8-1": { x: 2, y: 0, tilesetIdx: "1", tileSymbol: "·", isFlippedX: false },
            "9-1": { x: 2, y: 0, tilesetIdx: "1", tileSymbol: "·", isFlippedX: false },
            "10-1": { x: 3, y: 0, tilesetIdx: "1", tileSymbol: "¸", isFlippedX: false },
            "1-7": { x: 1, y: 1, tilesetIdx: "1", tileSymbol: "¼", isFlippedX: false },
            "1-6": { x: 1, y: 1, tilesetIdx: "1", tileSymbol: "¼", isFlippedX: false },
            "1-5": { x: 1, y: 1, tilesetIdx: "1", tileSymbol: "¼", isFlippedX: false },
            "1-4": { x: 1, y: 1, tilesetIdx: "1", tileSymbol: "¼", isFlippedX: false },
            "1-3": { x: 1, y: 1, tilesetIdx: "1", tileSymbol: "¼", isFlippedX: false },
            "1-2": { x: 1, y: 1, tilesetIdx: "1", tileSymbol: "¼", isFlippedX: false },
            "10-2": { x: 3, y: 1, tilesetIdx: "1", tileSymbol: "¾", isFlippedX: false },
            "10-3": { x: 3, y: 1, tilesetIdx: "1", tileSymbol: "¾", isFlippedX: false },
            "10-4": { x: 3, y: 1, tilesetIdx: "1", tileSymbol: "¾", isFlippedX: false },
            "10-5": { x: 3, y: 1, tilesetIdx: "1", tileSymbol: "¾", isFlippedX: false },
            "10-6": { x: 3, y: 1, tilesetIdx: "1", tileSymbol: "¾", isFlippedX: false },
            "10-7": { x: 3, y: 1, tilesetIdx: "1", tileSymbol: "¾", isFlippedX: false },
            "10-8": { x: 3, y: 1, tilesetIdx: "1", tileSymbol: "¾", isFlippedX: false },
            "10-9": { x: 3, y: 2, tilesetIdx: "1", tileSymbol: "Ä", isFlippedX: false },
            "9-9": { x: 2, y: 2, tilesetIdx: "1", tileSymbol: "Ã", isFlippedX: false },
            "8-9": { x: 2, y: 2, tilesetIdx: "1", tileSymbol: "Ã", isFlippedX: false },
            "7-9": { x: 2, y: 2, tilesetIdx: "1", tileSymbol: "Ã", isFlippedX: false },
            "6-9": { x: 2, y: 2, tilesetIdx: "1", tileSymbol: "Ã", isFlippedX: false },
            "5-9": { x: 2, y: 2, tilesetIdx: "1", tileSymbol: "Ã", isFlippedX: false },
            "2-8": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "5-8": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "6-8": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "7-8": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "9-8": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "8-8": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "8-7": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "9-7": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "9-6": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "9-5": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "9-4": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "9-3": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "9-2": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "8-2": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "7-2": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "6-2": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "5-2": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "4-2": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "3-2": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "2-2": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "2-3": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "2-4": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "2-5": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "2-6": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "2-7": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "3-7": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "3-6": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "3-5": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "3-4": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "3-3": { x: 4, y: 1, tilesetIdx: "1", tileSymbol: "¿", isFlippedX: false },
            "4-5": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "4-6": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "4-7": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "4-4": { x: 4, y: 1, tilesetIdx: "1", tileSymbol: "¿", isFlippedX: false },
            "4-3": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "6-3": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "6-4": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "6-5": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "6-6": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "5-6": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "5-7": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "6-7": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "7-7": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "8-6": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "8-5": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "8-4": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "8-3": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "7-4": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "7-5": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "7-6": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "7-3": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "5-3": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "5-4": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
            "5-5": { x: 2, y: 1, tilesetIdx: "1", tileSymbol: "½", isFlippedX: false },
          },
          visible: true,
          name: "Layer2",
          animatedTiles: {},
          opacity: 1,
        },
        {
          tiles: {
            "1-7": { x: 0, y: 2, tilesetIdx: "0", tileSymbol: "­", isFlippedX: false },
            "1-6": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "1-5": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "1-4": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "1-3": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "1-1": { x: 1, y: 0, tilesetIdx: "0", tileSymbol: "¦", isFlippedX: false },
            "1-2": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "2-1": { x: 2, y: 3, tilesetIdx: "0", tileSymbol: "³", isFlippedX: false },
            "3-1": { x: 2, y: 3, tilesetIdx: "0", tileSymbol: "³", isFlippedX: false },
            "4-1": { x: 2, y: 3, tilesetIdx: "0", tileSymbol: "³", isFlippedX: false },
            "5-1": { x: 2, y: 3, tilesetIdx: "0", tileSymbol: "³", isFlippedX: false },
            "6-1": { x: 2, y: 3, tilesetIdx: "0", tileSymbol: "³", isFlippedX: false },
            "7-1": { x: 2, y: 3, tilesetIdx: "0", tileSymbol: "³", isFlippedX: false },
            "8-1": { x: 2, y: 3, tilesetIdx: "0", tileSymbol: "³", isFlippedX: false },
            "9-1": { x: 2, y: 3, tilesetIdx: "0", tileSymbol: "³", isFlippedX: false },
            "10-1": { x: 3, y: 0, tilesetIdx: "0", tileSymbol: "¨", isFlippedX: false },
            "10-2": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "10-3": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "10-4": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "10-5": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "10-6": { x: 0, y: 1, tilesetIdx: "0", tileSymbol: "©", isFlippedX: false },
            "10-7": { x: 0, y: 2, tilesetIdx: "0", tileSymbol: "­", isFlippedX: false },
          },
          visible: true,
          name: "Layer3",
          animatedTiles: {},
          opacity: 1,
        },
      ],
      name: "Map 1",
      mapWidth: 12,
      mapHeight: 12,
      tileSize: 32,
      width: 320,
      height: 320,
      gridColor: "#00FFFF",
    },
  },
};

map.getTile2 = function (layer, col, row) {
  const mapInfo = this.tileMap.maps.Map_1.layers[layer].tiles;
  const colRow = col + "-" + row;
  if (mapInfo[colRow] === undefined) {
    return;
  }
  const tileData = this.tileMap.tileSets[mapInfo[colRow].tilesetIdx].tileData;
  const whatTile = {};
  Object.keys(tileData).forEach((key) => {
    if (tileData[key].tileSymbol === mapInfo[colRow].tileSymbol) {
      whatTile.x = tileData[key].x;
      whatTile.y = tileData[key].y;
    }
  });
  whatTile.tileSize = this.tileMap.tileSets[mapInfo[colRow].tilesetIdx].tileSize;
  whatTile.img = this.tileMap.tileSets[mapInfo[colRow].tilesetIdx].img;
  //   console.log(whatTile);
  return whatTile;
};

Game._drawTilesLayer = function (layer) {
  var startCol = Math.floor(this.camera.x / map.tsize);
  var endCol = startCol + this.camera.width / map.tsize;
  var startRow = Math.floor(this.camera.y / map.tsize);
  var endRow = startRow + this.camera.height / map.tsize;
  var offsetX = -this.camera.x + startCol * map.tsize;
  var offsetY = -this.camera.y + startRow * map.tsize;

  for (var c = startCol; c <= endCol; c++) {
    for (var r = startRow; r <= endRow; r++) {
      var tile = map.getTile2(layer, c, r);
      var x = (c - startCol) * map.tsize + offsetX;
      var y = (r - startRow) * map.tsize + offsetY;

      if (tile !== undefined) {
        // 0 => empty tile
        this.ctx.drawImage(
          this[tile.img], // image
          tile.x * tile.tileSize, // source x
          tile.y * tile.tileSize, // source y
          tile.tileSize, // source width
          tile.tileSize, // source height
          Math.round(x), // target x
          Math.round(y), // target y
          map.tsize, // target width
          map.tsize // target height
        );
      }
    }
  }
};

Game._drawTiles = function () {
  Game._drawTilesLayer(0);
  Game._drawTilesLayer(1);
  Game._drawTilesLayer(2);
};
